### PR TITLE
Serializer: writeUtf() fix to handle null strings in PHP 8.1

### PR DESCRIPTION
**Pull request by joshtynjala**

### CODE REVIEW

**Comment by lexoyo** [comment]
I continue to merge in the absence of a maintainer

**Comment by joshtynjala** [comment]
Thank you for merging! I'm mainly a frontend developer, so I'm not sure that I'm qualified to become a maintainer for this project. I don't really do any PHP or other backend work professionally. Nor have I used AMFPHP for real-world projects. One of my frontend open source libraries has a couple of samples that demonstrate how to communicate with AMFPHP, so I just wanted to be sure that they were still working with the latest PHP.

**Comment by lexoyo** [comment]
Ok
Let me know if you want to be co-maintainer with me
I'm not legitimate either

**Comment by joshtynjala** [comment]
@lexoyo Okay, I'll accept your invitation to be co-maintainer.

**Pull request merged**
